FROM gradle:jdk8-alpine as builder

COPY --chown=gradle:gradle . /src
WORKDIR /src
RUN gradle build

FROM openjdk:8-jre-alpine
EXPOSE 8080
COPY --from=builder /src/server/build/distributions/server.tar /app/

WORKDIR /app
RUN tar -xvf server.tar

WORKDIR /app/server

CMD bin/server
