package pw.forst.olb.common.config

const val SCHEDULING_SERVER_API_ADDRESS_ENV = "SERVER_ADDRESS"
const val REMOTE_SCHEDULER_API_ADDRESS_ENV = "CLIENT_ADDRESS"

const val SCHEDULING_SERVER_PORT = 8091
const val REMOTE_SCHEDULER_API_PORT = 8090

const val SCHEDULING_SERVER_API_ADDRESS = "localhost"
const val REMOTE_SCHEDULER_API_ADDRESS = "localhost"

val schedulingServerApiAddress = System.getenv(SCHEDULING_SERVER_API_ADDRESS_ENV) ?: SCHEDULING_SERVER_API_ADDRESS
val remoteSchedulerApiAddress = System.getenv(REMOTE_SCHEDULER_API_ADDRESS_ENV) ?: REMOTE_SCHEDULER_API_ADDRESS

val SCHEDULING_SERVER_API = "http://$schedulingServerApiAddress:$SCHEDULING_SERVER_PORT/v1"
val REMOTE_SCHEDULER_API = "http://$remoteSchedulerApiAddress:$REMOTE_SCHEDULER_API_PORT/v1"

